# golangci-lint v2.x configuration
# Minimal valid configuration for compatibility

version: "2"

run:
  timeout: 5m
  tests: false
  go: '1.21'

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
