# golangci-lint configuration
# Simplified configuration for compatibility

version: "2"

run:
  go: "1.21"
  timeout: 2m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false

output:
  formats:
    text:
      path: stdout
      colors: true
      print-issued-lines: true